apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tjbj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-tjbj@sha256:cb92cf27c17f74796a132addb4e2ebfdb447584f6e910a421cfa3118f2433e3a
        name: my-nodejs
        resources: {}
status: {}
